export interface MyMentorsModel {
    username: string,
    emailMentor: string,
    phoneNumber: string,
    passwordHash: string,
    createdAt: Date,
    isActive: boolean,
    isDeleted: boolean,
    bio: string,
    educationalInstitution: string,
    subject: string,
    message: string,
    starsNumber: number,
    reviewStatus: string,
    city: string,
    county: string,
    addressInfo: string,
}
